### ISSUE TITLE
App won't run on my phone

### ISSUE THREAD

**Issue by carlitaaz** [carlitaaz/HelloAndroid#1]
![image](https://user-images.githubusercontent.com/35874838/35474829-b8598aec-0361-11e8-96e6-958f23813e24.png)

![image](https://user-images.githubusercontent.com/35874838/35474836-cc8afdd4-0361-11e8-9469-d8bf11d035cf.png)

**Comment by carlitaaz** [comment]
This is the error on the phone:

FATAL EXCEPTION: main
                                                                                  Process: com.example.carlitaaz.helloandroid, PID: 5588
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.carlitaaz.helloandroid/com.example.carlitaaz.helloandroid.MainActivity}: android.view.InflateException: Binary XML file line #0: Can't convert value at index 4 to dimension: type=0x12
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                                   Caused by: android.view.InflateException: Binary XML file line #0: Can't convert value at index 4 to dimension: type=0x12
                                                                                   Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 4 to dimension: type=0x12
                                                                                      at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:737)
                                                                                      at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7607)
                                                                                      at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1925)
                                                                                      at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1824)
                                                                                      at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1823)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
                                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                      at com.example.carlitaaz.helloandroid.MainActivity.onCreate(MainActivity.java:11)
                                                                                      at android.app.Activity.performCreate(Activity.java:6942)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by carlitaaz** [comment]
SOLVED
the problem was that           android:layout_marginTop="@id/photo"        is not an acceptable line of code because I just learned that  you cannot give a view as margin.
